# Generated by Django 4.0.3 on 2022-03-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('quarter', models.IntegerField(null=True)),
                ('transcript', models.CharField(max_length=50)),
                ('company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='earningscall_api.companytype')),
            ],
        ),
    ]
